<?php

use App\Extensions\Catalog\Model\Order;
use Simflex\Core\Models\StructData;
use Simflex\Core\Models\StructField;
use Simflex\Core\Models\StructTable;
use Simflex\Core\Models\UserPriv;
use Simflex\Admin\Fields\FieldDateTime;
use Simflex\Admin\Fields\FieldDouble;
use Simflex\Admin\Fields\FieldEnum;
use Simflex\Admin\Fields\FieldFile;
use Simflex\Admin\Fields\FieldInt;
use Simflex\Admin\Fields\FieldNpp;
use Simflex\Admin\Fields\FieldString;
use Simflex\Admin\Fields\FieldTable;
use Simflex\Admin\Fields\FieldText;
use Simflex\Admin\Fields\FieldVirtualTable;

return new class implements \Simflex\Core\DB\Seeder {
    public function seed(): void
    {
        $stringField = StructField::byClass(FieldString::class);
        $intField = StructField::byClass(FieldInt::class);
        $dateTimeField = StructField::byClass(FieldDateTime::class);
        $textField = StructField::byClass(FieldText::class);
        $fileField = StructField::byClass(FieldFile::class);
        $enumField = StructField::byClass(FieldEnum::class);
        $nppField = StructField::byClass(FieldNPP::class);
        $doubleField = StructField::byClass(FieldDouble::class);
        $tableField = StructField::byClass(FieldTable::class);
        $virtualTableField = StructField::byClass(FieldVirtualTable::class);

        $adminPriv = UserPriv::byName('admin');

        $orderTable = StructTable::insertStatic([
            'name' => 'catalog_order',
            'order_by' => 'date',
            'order_desc' => true,
            'priv_add' => $adminPriv->priv_id,
            'priv_edit' => $adminPriv->priv_id,
            'priv_delete' => $adminPriv->priv_id,
            'class' => Order::class,
        ]);

        StructData::bulkInsert([
            [
                'npp' => 1,
                'table_id' => $orderTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'order_id',
                'label' => 'ID',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '1',
                        'e2n' => '1',
                        'hidden' => '1',
                        'width' => '60',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '54',
                        'pos' => '',
                        'pos_group' => '',
                        'is_fk' => '0',
                        'fk_table' => '',
                        'fk_key' => '',
                        'fk_label' => '',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 2,
                'table_id' => $orderTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'user_id',
                'label' => 'Пользователь',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '1',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                        'is_fk' => '1',
                        'fk_table' => 'user',
                        'fk_key' => 'user_id',
                        'fk_label' => 'login',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 3,
                'table_id' => $orderTable->table_id,
                'field_id' => $dateTimeField->field_id,
                'name' => 'date',
                'label' => 'Дата',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '120',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '576',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                    ],
                ])
                ,
            ],
            [
                'npp' => 4,
                'table_id' => $orderTable->table_id,
                'field_id' => $enumField->field_id,
                'name' => 'status',
                'label' => 'Статус',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '140',
                        'defaultValue' => 'new',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                        'enum' => 'new=Новый;;accepted=Принят;;pay=Ожидает оплаты;;sent=Доставляется;;delivered=Готов к выдаче;;finished=Получен;;canceled=Отменен',
                    ],
                ])
                ,
            ],
            [
                'npp' => 5,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'name',
                'label' => 'Имя',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Получатель',
                    ],
                ])
                ,
            ],
            [
                'npp' => 6,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'last_name',
                'label' => 'Фамилия',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '1',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Получатель',
                    ],
                ])
                ,
            ],
            [
                'npp' => 8,
                'table_id' => $orderTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'transcomp_id',
                'label' => 'Транспортная компания',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Получатель',
                        'is_fk' => '1',
                        'fk_table' => 'catalog_transcomp',
                        'fk_key' => 'transcomp_id',
                        'fk_label' => 'name',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 9,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'city',
                'label' => 'Город',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Получатель',
                    ],
                ])
                ,
            ],
            [
                'npp' => 10,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'address',
                'label' => 'Адрес',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Получатель',
                    ],
                ])
                ,
            ],
            [
                'npp' => 11,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'phone',
                'label' => 'Телефон',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '180',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Получатель',
                    ],
                ])
                ,
            ],
            [
                'npp' => 13,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'email',
                'label' => 'Почта',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '1',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '991',
                        'width_mob' => '190',
                        'pos' => 'right',
                        'pos_group' => 'Получатель',
                    ],
                ])
                ,
            ],
            [
                'npp' => 14,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'tracking',
                'label' => 'Номер для отслеживания',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                    ],
                ])
                ,
            ],
            [
                'npp' => 15,
                'table_id' => $orderTable->table_id,
                'field_id' => $doubleField->field_id,
                'name' => 'sum_total',
                'label' => 'Сумма',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '0',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '1',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Заказ',
                        'decimals' => '0',
                        'dec_point' => '.',
                        'thousands_sep' => ' ',
                    ],
                ])
                ,
            ],
            [
                'npp' => 16,
                'table_id' => $orderTable->table_id,
                'field_id' => $doubleField->field_id,
                'name' => 'sum_actual',
                'label' => 'Сумма со скидкой',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '0',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '1',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Заказ',
                        'decimals' => '0',
                        'dec_point' => '.',
                        'thousands_sep' => ' ',
                    ],
                ])
                ,
            ],
            [
                'npp' => 17,
                'table_id' => $orderTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'qty',
                'label' => 'Количество',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '1',
                        'width' => '0',
                        'defaultValue' => '0',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                        'is_fk' => '0',
                        'fk_table' => '',
                        'fk_key' => '',
                        'fk_label' => '',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 50,
                'table_id' => $orderTable->table_id,
                'field_id' => $virtualTableField->field_id,
                'name' => 'products',
                'label' => 'Товары',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                    ],
                ])
                ,
            ],
            [
                'npp' => 1,
                'table_id' => $orderTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'discount',
                'label' => 'Скидка (%)',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Заказ',
                        'is_fk' => '0',
                        'fk_table' => '',
                        'fk_key' => '',
                        'fk_label' => '',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 4,
                'table_id' => $orderTable->table_id,
                'field_id' => $fileField->field_id,
                'name' => 'invoice',
                'label' => 'Счет',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '1',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Загружаемые файлы',
                        'path' => '',
                    ],
                ])
                ,
            ],
            [
                'npp' => 52,
                'table_id' => $orderTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'total',
                'label' => 'Итого',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '1',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Заказ',
                    ],
                ])
                ,
            ],
            [
                'npp' => 5,
                'table_id' => $orderTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'payment_id',
                'label' => 'Способ оплаты',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                        'is_fk' => '1',
                        'fk_table' => 'catalog_payment',
                        'fk_key' => 'payment_id',
                        'fk_label' => 'name',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 1,
                'table_id' => $orderTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'delivery_sum',
                'label' => 'Стоимость доставки',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => 'right',
                        'pos_group' => 'Заказ',
                        'is_fk' => '0',
                        'fk_table' => '',
                        'fk_key' => '',
                        'fk_label' => '',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 500,
                'table_id' => $orderTable->table_id,
                'field_id' => $tableField->field_id,
                'name' => 'documents',
                'label' => 'Документы',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '0',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                        'struct' => '{"s":[{"n":"n","t":"text","l":"Имя","v":"","e":""},{"n":"t","t":"combo","l":"Тип","v":"text","e":"text=Текст,,int=Число,,combo=Список,,editor=Редактор,,image=Изображение,,file=Файл"},{"n":"l","t":"text","l":"Заголовок","v":"","e":""},{"n":"v","t":"text","l":"Значение","v":"","e":""},{"n":"e","t":"text","l":"Дополнительно","v":"","e":""}],"v":[{"n":"name","t":"text","l":"Название","v":"","e":"","__i":0},{"n":"date","t":"text","l":"Дата","v":"$DATE$","e":""},{"n":"sum","t":"text","l":"Сумма","v":"","e":"","__i":2},{"n":"file","t":"file","l":"Файл","v":"","e":"","__i":3}]}',
                    ],
                ])
                ,
            ],
        ]);

        $paymentTable = StructTable::insertStatic([
            'name' => 'catalog_payment',
            'order_by' => 'npp',
            'order_desc' => false,
            'priv_add' => $adminPriv->priv_id,
            'priv_edit' => $adminPriv->priv_id,
            'priv_delete' => $adminPriv->priv_id,
            'class' => null,
        ]);

        StructData::bulkInsert([
            [
                'npp' => 1,
                'table_id' => $paymentTable->table_id,
                'field_id' => $intField->field_id,
                'name' => 'payment_id',
                'label' => 'ID',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '1',
                        'e2n' => '1',
                        'hidden' => '1',
                        'width' => '60',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                        'is_fk' => '0',
                        'fk_table' => '',
                        'fk_key' => '',
                        'fk_label' => '',
                        'fk_is_pid' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 1,
                'table_id' => $paymentTable->table_id,
                'field_id' => $nppField->field_id,
                'name' => 'npp',
                'label' => '№ п/п',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => 1,
                        'hidden' => '0',
                        'width' => '80',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                    ],
                ])
                ,
            ],
            [
                'npp' => 3,
                'table_id' => $paymentTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'name',
                'label' => 'Название',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '1',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '1',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                    ],
                ])
                ,
            ],
            [
                'npp' => 4,
                'table_id' => $paymentTable->table_id,
                'field_id' => $stringField->field_id,
                'name' => 'class',
                'label' => 'Обработчик',
                'help' => 'Класс PHP',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                    ],
                ])
                ,
            ],
            [
                'npp' => 5,
                'table_id' => $paymentTable->table_id,
                'field_id' => $textField->field_id,
                'name' => 'desc',
                'label' => 'Описание',
                'help' => '',
                'placeholder' => '',
                'params' => serialize([
                    'main' => [
                        'pk' => '0',
                        'e2n' => '1',
                        'hidden' => '0',
                        'width' => '0',
                        'defaultValue' => '',
                        'required' => '0',
                        'filter' => '0',
                        'onchange' => '',
                        'readonly' => '0',
                        'style_cell' => '',
                        'screen_width' => '0',
                        'width_mob' => '0',
                        'pos' => '',
                        'pos_group' => '',
                        'editor_mini' => '0',
                        'editor_full' => '0',
                    ],
                ])
                ,
            ],
        ]);
    }
};